# Generated by Django 2.0.13 on 2020-07-07 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_status', models.CharField(max_length=16)),
                ('meter_reading', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='usermeter',
            name='configurations',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermeter',
            name='install_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermeter',
            name='location',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermeter',
            name='model_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermeter',
            name='siteid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermeter',
            name='warranty',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='meterhealth',
            name='user_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meterhealths', to='meters.UserMeter'),
        ),
    ]
