# Generated by Django 2.0.13 on 2020-07-11 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_auto_20200708_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterhealth',
            name='reading_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
