# Generated by Django 2.2.13 on 2020-07-18 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meters', '0004_meterhealth_reading_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=128)),
                ('api_name', models.CharField(max_length=32)),
                ('api_method', models.CharField(choices=[('C', 'Post'), ('R', 'Get'), ('U', 'Put'), ('D', 'Delete')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('api_permissions', models.ManyToManyField(to='meters.ApiPermission')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
